Create XPAND
  /*   Rexx */                                                                  
  /*         rexx program to restore a member to last saved State */            
/*   */                                                                         
  Call 1000_Initialize                                                          
  Call 2000_Process                                                             
  Call Exit_Rexx                                                                
  /* End of Main Program */                                                     
  1000_Initialize:                                                              
    Signal on Error                                                             
    G. = ""                                                                     
    G.REXX.LINEPLUS = 0                                                         
    G.REXX.COPY.TCS = 0                                                         
    Call 1100_GetParms                                                          
                                                                                
    Call 1200_Get_Member_Detail                                                 
    Etype = 1300_Get_Element_Type()                                             
    If Etype /= "COB" Then                                                      
    Do                                                                          
      Say "Xpand will work Only on COBOL elements as of now"                    
      Call Exit_Rexx                                                            
    End                                                                         
    Call XXXX_BackUp                                                            
    Return                                                                      
  /*-----------------------------------------------------*/                     
  /*       Receive Inline parameters                     */                     
  1100_GetParms: Procedure Expose G.                                            
    ADDRESS ISREDIT "MACRO (CMDPARM) PROCESS"                                   
    G.ParmIn = CMDPARM                                                          
    Return                                                                      
  /*-----------------------------------------------------*/                     
  1200_Get_Member_Detail: Procedure Expose G.                                   
    Call XXXX_ISREDIT(" (MEM1) = MEMBER ")                                      
    Call XXXX_ISREDIT(" (DSN1) = DATASET ")                                     
    G.REXX.MEMBER  = MEM1                                                       
    G.REXX.DATASET = DSN1                                                       
    Return                                                                      
  /*-----------------------------------------------------*/                     
  1300_Get_Element_Type: Procedure                                              
    Type = "UNKNOWN"                                                            
    Call XXXX_ISREDIT(" (LINENUM1) = LINENUM .ZL")                              
    If LINENUM1 <= 0 then                                                       
    Do                                                                          
       Say "Empty file. Please check"                                           
       Call Exit_Rexx                                                           
    End                                                                         
    Call XXXX_ISREDIT(" (LINE1) = LINE 1 ")                                     
    Select                                                                      
     when Substr(LINE1,1,2) = "//"  then                                        
     Do                                                                         
       Type = "JCL"                                                             
     End                                                                        
     when Index(LINE1," DIVISION. ") > 0  then                                  
     Do                                                                         
       Type = "COB"                                                             
     End                                                                        
     when Index(LINE1," REXX ") > 0  then                                       
     Do                                                                         
       Type = "REXX"                                                            
     End                                                                        
     /* Keep adding code for other types */                                     
     Otherwise                                                                  
     Do                                                                         
       Type = "UNKNOWN"                                                         
     End                                                                        
    end                                                                         
    Return Type                                                                 
  /*-----------------------------------------------------*/                     
  XXXX_BackUp: Procedure Expose G.                                              
    Call XXXX_ISREDIT("cut Backup .zf .zl ")                                    
                                                                                
    Return                                                                      
  /*-----------------------------------------------------*/                     
  XXXX_Restore: Procedure Expose G.                                             
                                                                                
    Call XXXX_ISREDIT("delete .zf .zl ")                                        
    Call XXXX_ISREDIT("paste backup ")                                          
                                                                                
    Return                                                                      
  /*-----------------------------------------------------*/                     
  2000_Process: Procedure Expose G.                                             
    Call 2100_ReadLines                                                         
    Call 2100_Get_CopyNames                                                     
    Call 2300_Expand_copy                                                       
    Call XXXX_ISREDIT(" C X'FA' ''' all ")                                      
    Call XXXX_ISREDIT(" Locate .ZFirst ")                                       
    Call XXXX_ISREDIT(" Reset ")                                                
    Return                                                                      
  /*-----------------------------------------------------*/                     
  2100_ReadLines: Procedure Expose G.                                           
                                                                                
    CALL XXXX_ISREDIT(" NUM ON STD COB")                                        
    CALL XXXX_ISREDIT(" RENUM ")                                                
    Call XXXX_ISREDIT(" NUM OFF")                                               
    Call XXXX_ISREDIT(" (BOT) = LINENUM .ZL")                                   
    Call XXXX_ISREDIT(" (LINE1) = LINE 1")                                      
                                                                                
    StartLine = Substr(LINE1,73,6)                                              
                                                                                
    If BOT > 1 Then                                                             
    DO                                                                          
     Call XXXX_ISREDIT(" (LINE1) = LINE 2")                                     
     NextLine = Substr(LINE1,73,6)                                              
     Increment = NextLine - StartLine                                           
    End                                                                         
    Else                                                                        
    Do                                                                          
     G.REXX.LINES.NUMERS.Incr = 1                                               
    End                                                                         
    Call XXXX_ISREDIT(" X '*' 7 all ")                                          
    Call XXXX_ISREDIT(" delete x all")                                          
    Call XXXX_ISREDIT(" X all ")                                                
    Call XXXX_ISREDIT(" F ' COPY ' all ")                                       
    Call XXXX_ISREDIT(" F ' INCLUDE ' all ")                                    
    Call XXXX_ISREDIT(" delete x all")                                          
    Call XXXX_ISREDIT(" (BOT) = LINENUM .ZL")                                   
                                                                                
    TOP = 1                                                                     
    Do LS = TOP to BOT                                                          
      Call XXXX_ISREDIT(" (LINE1) = LINE " || LS )                              
      G.REXX.LINES.LS = Substr(LINE1,1,72)                                      
                                                                                
      G.REXX.LINES.LS.LN = ((Substr(LINE1,73,6) - StartLine ) ,                 
                           / Increment) + 1                                     
    End                                                                         
    G.REXX.LINES.TLS = BOT                                                      
 /* Call XXXX_ISREDIT(" RESTORE1 ") */                                          
    Call XXXX_Restore                                                           
    Return                                                                      
  /*-----------------------------------------------------*/                     
  2100_Get_CopyNames: Procedure Expose G.                                       
    CS = 0                                                                      
    Do LS = 1 to G.REXX.LINES.TLS                                               
      Parse Var G.REXX.LINES.LS ,                                               
            Word.1 Word.2 Word.3 Word.4 Word.5 Word.6 Word.7 .                  
      Do I = 1 to 7                                                             
         If Word.I = "COPY" |  Word.I = "INCLUDE" Then                          
         Do                                                                     
           I = I + 1                                                            
           CS = CS + 1                                                          
           G.REXX.COPY.CS = Translate(Word.I,"",".")                            
           G.REXX.COPY.CS = Translate(G.REXX.COPY.CS,"",",")                    
           G.REXX.COPYLN.CS = G.REXX.LINES.LS.LN                                
           G.REXX.COPY.TCS = CS                                                 
           Leave                                                                
         End                                                                    
      End                                                                       
    End                                                                         
    Return                                                                      
  /*-----------------------------------------------------*/                     
                                                                                
  2300_Expand_copy: Procedure Expose G.                                         
                                                                                
    Do CS = 1 to G.REXX.COPY.TCS                                                
     /*Say "Expanding --> " G.REXX.COPY.CS */                                   
       If G.REXX.COPY.CS = "SQLCA" Then                                         
       Do                                                                       
          Iterate                                                               
       End                                                                      
       G.REXX.COPY.CS = "'VPRDEND.PRD.COPYLIB(" || ,                            
                        strip(G.REXX.COPY.CS) || ")'"                           
       If SYSDSN(G.REXX.COPY.CS) /= "OK" Then                                   
       Do                                                                       
          Say "Can not open" G.REXX.COPY.CS                                     
          Leave                                                                 
       End                                                                      
       "Alloc F(in) DS(" || G.REXX.COPY.CS || ")shr"                            
       "Execio * diskr in (finis stem in."                                      
       "Free F(in)"                                                             
       Do I = 1 to in.0                                                         
         LineNum = G.REXX.COPYLN.CS + G.REXX.LINEPLUS                           
         LINEDAT = "'#XPAND*>" || ,                                             
                   Translate(SubStr(in.i,7,65),'FA'X,"'") || "'"                
         Cmd = " LINE_AFTER " || LineNum || " = DATALINE + &LINEDAT "           
                                                                                
         Call XXXX_ISREDIT(Cmd)                                                 
         G.REXX.LINEPLUS  = G.REXX.LINEPLUS + 1                                 
       end                                                                      
    End                                                                         
    Return                                                                      
  /*-----------------------------------------------------*/                     
  XXXX_ISREDIT:                                                                 
    Arg Cmd                                                                     
    ADDRESS ISREDIT Cmd                                                         
    Return                                                                      
  /*-----------------------------------------------------*/                     
  Exit_Rexx: Procedure                                                          
    Exit                                                                        
  Error:                                                                        
    Say "Error Occured. Return Code: " RC                                       
    Call Exit_Rexx